server:
  port: 8080
  servlet:
    context-path: /
spring:
  profiles:
    active: dev
  freemarker:
    cache: false
    charset: utf-8
    content-type: text/html
    enabled: true
    settings:
      number_format: '0'

pagehelper:
  autoDialect: true
  closeConn: true
  reasonable: true

logging:
  path: /data/logs/wx-inspect-transaction-single
  file: wx-transactionsingle
  level:
    root: info

mybatis:
  type-aliases-package: com.wx.inspect.transaction.single.po
  mapper-locations: classpath:/mappers/**Mapper.xml